language: ruby
branches:
  only:
  - master
rvm:
- 2.3.1
script: gulp && bundle exec jekyll build
exclude: [vendor]
sudo: false
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh-pages
  name: Deployment Bot
