---
title: Social Mediation
timezone: UTC
collections:
  contributors:
    title: Contributors
    output: false
  episodes:
    title: Episodes
    output: true
    permalink: "/episode/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: contributors
  values:
    image:
    is host: false
    links:
    - id:
      url:
- scope:
    path: ''
    type: episodes
  values:
    contributors: []
    layout: episode
- scope:
    path: ''
    type: posts
  values:
    layout: post
    contributors:
    featured-image:
email: hello@socialmediation.show
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl:
url: http://socialmediation.show
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
- jekyll-feed
- jekyll-paginate-v2
exclude:
- Gemfile
- Gemfile.lock
- vendor
permalink: pretty
pagination:
  enabled: true
  per_page: 2
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2
