---
title: Social Mediation
timezone: UTC
collections:
  contributors:
    title: Contributors
    output: false
  episodes:
    title: Episodes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: contributors
  values:
    image:
    is host: false
    links:
    - id:
      url:
- scope:
    path: ''
    type: episodes
  values:
    contributors: []
    layout: episode
- scope:
    path: ''
    type: posts
  values:
    layout: post
    contributors:
    featured-image: 
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl:
url:
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
- jekyll-feed
